/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

class Game(player1: Player, player2: Player) {
    var player1Points = player1.getPoints()
    var player2Points = player2.getPoints()

    fun getScore() {

    }


}

fun main() {

}
