/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

import org.assertj.core.api.Assertions
import org.junit.jupiter.api.Test

class PlayerTest {

    @Test
    fun initialScoreForBothPlayersIs0() {
        val classUnderTest = Player()
        Assertions.assertThat(classUnderTest.points).isEqualTo(0)
    }

    @Test
    fun increaseScore() {

    }
}
